### ISSUE TITLE
removeAll() is not clearing data from cache memory

### ISSUE THREAD

**Issue by vasuthakker** [rommansabbir/StoreX#2]
removeAll() is not clearing data from cache memory, Still I can retrieve the same data using the same key after calling removeAll() function. 

It should not have given me the data after calling the function.

**Comment by rommansabbir** [comment]
Note:
- `remove(key: String)` to delete the stored data from SharedPref or Cache Dir based on Config.
- New API `removeFromCacheDir(key: List<String>): Boolean` is to delete data from Cache Dir only.
