### ISSUE TITLE
StoreAbleObject for standard types? Int, String, Boolean, Long etc

### ISSUE THREAD

**Issue by IODevBlue** [rommansabbir/StoreX#5]
To save values in the cache, each object has to be wrapped as a StoreAbleObject.

Which means that even String, Int, Long etc..these would have to be wrapped as a StoreAbleObject.

It would be nice to have a library provision for these Kotlin types which can be extended rather than creating them separately.

String - StoreAbleString
Int - StoreAbleInt
Long - StoreAbleLong
Double - StoreAbleDouble
Byte - StoreAbleByte
Char - StoreAbleChar
Short - StoreAbleShort
...and so on.

Performing the same function as the StoreAbleObject but for Kotlin library data types.

If it is possible to include provision for Collection types too, that'll be nice.
ArrayList - StoreAbleArrayList
Set - StoreAbleSet

**Comment by rommansabbir** [comment]
Sure. I will work on this changes.

**Comment by rommansabbir** [comment]
Added on the new version.
